<a href="https://colab.research.google.com/github/roneshpra/PythonLearning/blob/Dev/PythonBasics/Python_Wk2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np  # Import numpy library to use its functions
import pandas as pd  # Import pandas library to use its functions

In [ ]:
## Numpy Arrays ##
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']
arr_num = [1, 2, 3, 4, 5]

py_arr_str = np.array(arr_str)
py_arr_num = np.array(arr_num)

print(py_arr_str)
print(py_arr_num)
print(type(arr_str))
print(type(py_arr_str))
print(type(py_arr_num))


matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
['1' '2' '3' '4' '5']
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
## Numpy Functions ##

vec = np.arange(0, 10, 2)
print("Arange :", vec)

vec1 = np.linspace(0, 10, 2)
print("Linspace :", vec1)

vec2 = np.zeros([3, 4])
print("Matrix Zeroes :\n", vec2)

vec3 = np.ones([3,4])
print("Matrix Ones :\n", vec3)

vec4 = np.eye(4)
print("Identity Matrix :\n", vec4)

Arange : [0 2 4 6 8]
Linspace : [ 0. 10.]
Matrix Zeroes :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrix Ones :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.arange(0, 10)
arr_reshape = arr.reshape(2, 5)
print(arr)
print(arr_reshape)

arr1 = np.array([1, 2, 3, 4])
expo = np.exp(arr1)
print("Exponentiation of arr1 is", expo)

logarithm = np.log(arr1)
print("Logarithm of arr1 is", logarithm)

logarithm10 = np.log10(arr1)
print("Logarithm10 of arr1 is", logarithm10)

logarithm2 = np.log2(arr1)
print("Logarithm2 of arr1 is", logarithm2)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
Exponentiation of arr1 is [ 2.71828183  7.3890561  20.08553692 54.59815003]
Logarithm of arr1 is [0.         0.69314718 1.09861229 1.38629436]
Logarithm10 of arr1 is [0.         0.30103    0.47712125 0.60205999]
Logarithm2 of arr1 is [0.        1.        1.5849625 2.       ]


In [ ]:
## Arithmetic Functions ##
arr_math1 = np.arange(1, 6)
arr_math2 = np.arange(3, 8)

print("Array 1 is :", arr_math1)
print("Array 2 is :", arr_math2)

# Arithmetic operations

print("Addition :", arr_math1 + arr_math2)
print("Subtraction :", arr_math1 - arr_math2)
print("Multiplication :", arr_math1 * arr_math2)
print("Division :", arr_math1 / arr_math2)
print("Inverse :", 1/arr_math1)
print("Power :", arr_math1 ** arr_math2)


Array 1 is : [1 2 3 4 5]
Array 2 is : [3 4 5 6 7]
Addition : [ 4  6  8 10 12]
Subtraction : [-2 -2 -2 -2 -2]
Multiplication : [ 3  8 15 24 35]
Division : [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse : [1.         0.5        0.33333333 0.25       0.2       ]
Power : [    1    16   243  4096 78125]


In [ ]:
## Matrix Operations

matrix1 = np.arange(1, 10).reshape(3, 3)
matrix2 = np.arange(11, 20).reshape(3, 3)

print("Matrix 1 is :\n", matrix1)
print("Matrix 2 is :\n", matrix2)

print("Addition :\n", matrix1 + matrix2)
print("Subtraction :\n", matrix1 - matrix2)
print("Multiplication :\n", matrix1 * matrix2)
print("Division :\n", matrix1 / matrix2)
print("Linear multiplication is :\n", matrix1 @ matrix2)

print("Transpose :\n", matrix1.T)

Matrix 1 is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2 is :
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Addition :
 [[12 14 16]
 [18 20 22]
 [24 26 28]]
Subtraction :
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
Multiplication :
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
Division :
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
Linear multiplication is :
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]
Transpose :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
vec1 = np.linspace(20, 50, 4)
vec2 = np.linspace(100, 120, 4)

print(vec1)
print(vec2)

print(vec1 + vec2)

[20. 30. 40. 50.]
[100.         106.66666667 113.33333333 120.        ]
[120.         136.66666667 153.33333333 170.        ]


In [ ]:
rand_mat = np.random.randn(5, 5)
print(rand_mat[rand_mat > 0])
print(np.mean(rand_mat))
print(np.std(rand_mat))
#np.min(rand_mat)
#np.max(rand_mat)

[1.67180763 0.61416581 0.77626551 1.30030069 0.34634355 1.43517713
 0.17332629 0.30829826 1.25503572]
-0.1535943435056858
0.9483041196418305


In [ ]:
arr_rand = np.random.randn(5,5)
print(arr_rand)
print(arr_rand[arr_rand < 0])
arr_rand[arr_rand < 0] = 0
arr_rand[arr_rand > 0] = 1
print(arr_rand)
print(arr_rand[0][1])
print(arr_rand[0,1])
print(arr_rand[0:2, 0:2])

[[-0.56517084  0.24257675  0.9903457  -0.11882991  0.47986519]
 [-0.52144492 -0.15509491  0.62474989 -1.37618453  0.17572495]
 [-0.78458672  0.43390442 -1.36627936  0.67944165  0.04128227]
 [ 1.6562056  -0.5561772   0.80315303 -0.72438189  1.72435306]
 [-0.78834153 -2.80410348  0.2997194  -0.86012374 -1.04384292]]
[-0.56517084 -0.11882991 -0.52144492 -0.15509491 -1.37618453 -0.78458672
 -1.36627936 -0.5561772  -0.72438189 -0.78834153 -2.80410348 -0.86012374
 -1.04384292]
[[0. 1. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 1.]
 [1. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0.]]
1.0
1.0
[[0. 1.]
 [0. 0.]]


In [3]:
### Pandas ###
med_price_list = [55, 25, 75, 40, 90]
med_price_array = np.array(med_price_list)
med_price_list_series = pd.Series(med_price_list)
med_price_array_series = pd.Series(med_price_array)
print(med_price_list_series)
print(med_price_array_series)

0    55
1    25
2    75
3    40
4    90
dtype: int64
0    55
1    25
2    75
3    40
4    90
dtype: int64


In [14]:
# changing the index of the series
med_price_list_labeled = pd.Series(med_price_list, index=['Lisinopril', 'Metformin', 'Novolog', 'Farxiga', 'Tresiba'])
print(med_price_list_labeled)

Lisinopril    55
Metformin     25
Novolog       75
Farxiga       40
Tresiba       90
dtype: int64


In [15]:
# adding 4 to existing price
med_price_list_labeled = med_price_list_labeled + 4
print("Old Price List")
print(med_price_list_labeled)

print("")

new_price_list = [60, 60, 100, 60, 100]
new_price_list_labeled = pd.Series(new_price_list, index=['Lisinopril', 'Metformin', 'Novolog', 'Farxiga', 'Tresiba'])
print("New Price List")
print(new_price_list_labeled)

# Difference between original list and new list
print("")
print("Difference between new price and old price")
print(new_price_list_labeled - med_price_list_labeled)

Old Price List
Lisinopril    59
Metformin     29
Novolog       79
Farxiga       44
Tresiba       94
dtype: int64

New Price List
Lisinopril     60
Metformin      60
Novolog       100
Farxiga        60
Tresiba       100
dtype: int64

Difference between new price and old price
Lisinopril     1
Metformin     31
Novolog       21
Farxiga       16
Tresiba        6
dtype: int64


In [18]:
## Panda Data Frames ##
student = ['Tisha', 'Adhvika', 'Ishaanvi', 'Ivanka', 'Sawyer']
df1 = pd.DataFrame(student, columns = ['StudentName'])
df1

grades = ['A+', 'B+', 'A-', 'B-', 'C+']
df2 = pd.DataFrame({'StudentName': student, 'Grades': grades})
df2

StudentName Grades
0       Tisha     A+
1     Adhvika     B+
2    Ishaanvi     A-
3      Ivanka     B-
4      Sawyer     C+

In [20]:
# access series
provider = ['AT&T', 'Verizon', 'T-Mobile', 'Jio', 'Airtel']
roi = [1234.5, 1113.4, 1013.2, 966.8, 735.9]

telecom = pd.Series(roi, index = provider)
telecom


AT&T        1234.5
Verizon     1113.4
T-Mobile    1013.2
Jio          966.8
Airtel       735.9
dtype: float64

In [30]:
print(telecom[0])
print(telecom['AT&T'])
print(telecom[:3])
print(telecom[:'Jio'])

1234.5
1234.5
AT&T        1234.5
Verizon     1113.4
T-Mobile    1013.2
dtype: float64
AT&T        1234.5
Verizon     1113.4
T-Mobile    1013.2
Jio          966.8
dtype: float64


<ipython-input-30-9aeef9d1232d>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(telecom[0])


In [26]:

telecom.iloc[0]

1234.5


np.float64(1234.5)