<a href="https://colab.research.google.com/github/roneshpra/PythonLearning/blob/Dev/PythonBasics/Python_Wk2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np  # Import numpy library to use its functions

In [10]:
## Numpy Arrays ##
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']
arr_num = [1, 2, 3, 4, 5]

py_arr_str = np.array(arr_str)
py_arr_num = np.array(arr_num)

print(py_arr_str)
print(py_arr_num)
print(type(arr_str))
print(type(py_arr_str))
print(type(py_arr_num))


matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
['1' '2' '3' '4' '5']
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
## Numpy Functions ##

vec = np.arange(0, 10, 2)
print("Arange :", vec)

vec1 = np.linspace(0, 10, 2)
print("Linspace :", vec1)

vec2 = np.zeros([3, 4])
print("Matrix Zeroes :\n", vec2)

vec3 = np.ones([3,4])
print("Matrix Ones :\n", vec3)

vec4 = np.eye(4)
print("Identity Matrix :\n", vec4)

Arange : [0 2 4 6 8]
Linspace : [ 0. 10.]
Matrix Zeroes :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrix Ones :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
